//$file${Active_Objects::Blinky_AO.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Publish_Subscirbe.qm
// File:  ${Active_Objects::Blinky_AO.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Active_Objects::Blinky_AO.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "Blinky_AO.h"

//$declare${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky} .............................................................
typedef struct Blinky {
// protected:
    QActive super;

// public:
} Blinky;

extern Blinky Blinky_inst;

// protected:
static QState Blinky_initial(Blinky * const me, void const * const par);
static QState Blinky_HSM(Blinky * const me, QEvt const * const e);
static QState Blinky_ON(Blinky * const me, QEvt const * const e);
static QState Blinky_OFF(Blinky * const me, QEvt const * const e);
//$enddecl${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared::Blinky_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Blinky_ctor} .....................................................
void Blinky_ctor(void) {
    Blinky * const me = &Blinky_inst;
    QActive_ctor(&me->super,Q_STATE_CAST(&Blinky_initial));
}
//$enddef${Shared::Blinky_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared::Blinky_AO} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Blinky_AO} .......................................................
QActive *const Blinky_AO =&Blinky_inst.super;
//$enddef${Shared::Blinky_AO} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky} .............................................................
Blinky Blinky_inst;

//${AOs::Blinky::SM} .........................................................
static QState Blinky_initial(Blinky * const me, void const * const par) {
    //${AOs::Blinky::SM::initial}
    Q_UNUSED_PAR(par);
    QActive_subscribe((QActive *)me,BTN_PRESSED_SIG);
    QS_OBJ_DICTIONARY(&Blinky_inst);
    QS_SIG_DICTIONARY(BTN_PRESSED_SIG,    (void *)0);
    return Q_TRAN(&Blinky_ON);
}

//${AOs::Blinky::SM::HSM} ....................................................
static QState Blinky_HSM(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::HSM::ON} ................................................
static QState Blinky_ON(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::HSM::ON}
        case Q_ENTRY_SIG: {
            BSP_Toggle();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky::SM::HSM::ON::BTN_PRESSED}
        case BTN_PRESSED_SIG: {
            status_ = Q_TRAN(&Blinky_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_HSM);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::HSM::OFF} ...............................................
static QState Blinky_OFF(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::HSM::OFF}
        case Q_ENTRY_SIG: {
            BSP_Toggle();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky::SM::HSM::OFF::BTN_PRESSED}
        case BTN_PRESSED_SIG: {
            status_ = Q_TRAN(&Blinky_ON);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_HSM);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
